services:
  - type: web
    name: SolfeoUPCH
    env: python
    region: oregon
    branch: jesus
    buildCommand: |
      apt-get update
      apt-get install -y fluidsynth fluid-soundfont-gm lilypond timidity
      pip install -r requirements.txt
    startCommand: gunicorn web_app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"